/**
 * Bakes the built frontend into a TypeScript module so `bun build --compile`
 * can put it inside the executable.
 *
 * Run after `vite build` and before the compile step. Writing a module rather
 * than relying on import attributes keeps this working with Vite's hashed
 * asset names, which change on every build and so cannot be named in a static
 * import.
 */
import { readdirSync, readFileSync, mkdirSync, writeFileSync, statSync } from 'node:fs';
import { relative, resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const dist = resolve(root, 'web', 'dist');
const out = resolve(root, 'server', 'generated', 'web-assets.ts');

const TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.map': 'application/json',
};

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = resolve(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files: Record<string, { type: string; b64: string }> = {};
let bytes = 0;

for (const full of walk(dist)) {
  const rel = relative(dist, full).replaceAll('\\', '/');
  const data = readFileSync(full);
  const ext = rel.slice(rel.lastIndexOf('.'));
  files[rel] = { type: TYPES[ext] ?? 'application/octet-stream', b64: data.toString('base64') };
  bytes += data.length;
}

mkdirSync(resolve(root, 'server', 'generated'), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/embed-web.ts — do not edit.\n` +
    `export const files: Record<string, { type: string; b64: string }> = ${JSON.stringify(
      files,
      null,
      1,
    )};\n`,
);

console.log(
  `[embed] ${Object.keys(files).length} files, ${(bytes / 1024).toFixed(0)} KB -> ${relative(root, out)}`,
);
